import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import test from 'node:test';
import vm from 'node:vm';
const require=createRequire(import.meta.url);
const ts=require('typescript');
const source=readFileSync(new URL('../src/lib/auth/session.ts',import.meta.url),'utf8');
function sessionHarness(){const mapStorage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}};const localStorage=mapStorage(),sessionStorage=mapStorage();const context={exports:{},localStorage,sessionStorage,window:{dispatchEvent:()=>{}},Event:class {}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,context);return {...context,...context.exports};}
test('session-only sign-in does not persist in remembered storage',()=>{const h=sessionHarness();h.saveSessionToken('sample-session');assert.equal(h.localStorage.getItem('medguide_token'),null);assert.equal(h.sessionStorage.getItem('medguide_token'),'sample-session');assert.equal(h.getSessionToken(),'sample-session');});
test('remembered sign-in replaces a previous session token',()=>{const h=sessionHarness();h.saveSessionToken('old-session');h.saveSessionToken('remembered',true);assert.equal(h.sessionStorage.getItem('medguide_token'),null);assert.equal(h.localStorage.getItem('medguide_token'),'remembered');assert.equal(h.getSessionToken(),'remembered');});
test('sign-out clears both storage locations',()=>{const h=sessionHarness();h.sessionStorage.setItem('medguide_token','session');h.localStorage.setItem('medguide_token','remembered');h.clearSession();assert.equal(h.getSessionToken(),null);});
test('return destination rejects outside URLs and preserves application entry',()=>{const h=sessionHarness();for(const v of [null,'https://example.com','//example.com','/about','/app/\\example.com'])assert.equal(h.safeReturnPath(v),'/app/dashboard');assert.equal(h.safeReturnPath('/app/chat'),'/app/chat');});
const root=new URL('../.next/server/app/',import.meta.url);
const html=route=>readFileSync(new URL(`${route}.html`,root),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
test('authentication pages expose distinct intents and accessible credentials',()=>{const login=html('login'),signup=html('register');assert.match(login,/Welcome back to MedGuide/);assert.match(signup,/Create your MedGuide account/);assert.match(login,/autocomplete="current-password"/i);assert.match(signup,/autocomplete="new-password"/i);assert.match(signup,/minLength="8"/i);assert.match(signup,/Confirm password/);assert.match(signup,/name="terms"[^>]*required|name="terms"/);assert.match(login,/Remember me on this device/);for(const page of [login,signup]){assert.equal((page.match(/<main\b/g)||[]).length,1);assert.match(page,/Preview mode/);assert.match(page,/aria-label="Show password"/);assert.doesNotMatch(page,/Continue with Google|Encrypted patient authentication|demo_google_token/);}});
test('unconnected account recovery cannot imply an email was sent',()=>{assert.match(html('forgot-password'),/Password recovery is not connected yet/);assert.match(html('verify-email'),/No verification code has been sent/);});
test('previous broken product destinations render the protected account gate',()=>{for(const path of ['app/prescriptions','app/prescriptions/upload','app/medications/history'])assert.match(html(path),/Checking account access/);});
function clientHarness(fetchImpl){const apiSource=readFileSync(new URL('../src/lib/api/client.ts',import.meta.url),'utf8');const context={exports:{},fetch:fetchImpl,require:name=>{if(name==='./config')return {API_BASE_URL:'http://example.invalid/api/v1',isMockMode:()=>false};if(name==='./mock-adapter')return {MockApiAdapter:{}};if(name==='@/lib/auth/session')return {getSessionToken:()=>null};throw new Error(`Unexpected runtime dependency: ${name}`);}};vm.runInNewContext(ts.transpileModule(apiSource,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,context);return context.exports.api;}
test('failed HTTP authentication responses cannot be treated as successful sessions',async()=>{const api=clientHarness(async()=>({ok:false,json:async()=>({success:true,message:'Service unavailable',data:{access_token:'invalid-test-token'}})}));for(const result of [await api.login({email_or_phone:'synthetic@example.com',password:'sample'}),await api.register({full_name:'Synthetic',email:'synthetic@example.com',password:'sample'})]){assert.equal(result.success,false);assert.equal(result.data,undefined);assert.equal(result.message,'Service unavailable');}});
test('network authentication failure stays an error instead of granting a session',async()=>{const api=clientHarness(async()=>{throw new Error('Connection unavailable')});await assert.rejects(api.login({email_or_phone:'synthetic@example.com',password:'sample'}),/Connection unavailable/);});
