"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AuthFrame } from "@/components/auth/auth-experience";
import { useLanguage } from "@/lib/i18n/context";
import styles from "@/components/auth/auth-experience.module.css";
export default function OnboardingPage() { const router = useRouter(); const { language, setLanguage } = useLanguage(); const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false); function finish(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!ready)
    return; setSaving(true); router.replace("/app/dashboard"); } return <AuthFrame kind="register"><h2>Make MedGuide feel familiar.</h2><p className={styles.intro}>Choose your language, understand the boundaries, and continue to your workspace.</p><form className={styles.form} onSubmit={finish}><label className={styles.select}>Preferred language<select value={language} onChange={e => setLanguage(e.target.value as "en" | "hi" | "te")}><option value="en">English</option><option value="hi">हिंदी</option><option value="te">తెలుగు</option></select></label><p className={styles.status}>MedGuide provides information to support conversations with qualified healthcare professionals. It does not provide a definitive diagnosis or change prescribed treatment. This version uses sample information; do not enter real health records.</p><label className={styles.check}><input type="checkbox" required checked={ready} onChange={e => setReady(e.target.checked)}/><span>I understand the <Link href="/legal/disclaimer">medical boundaries</Link> and the <Link href="/privacy">privacy information</Link>.</span></label><button type="submit" disabled={saving} className={styles.submit}>{saving ? "Opening your workspace…" : "Finish setup →"}</button></form><p className={styles.switch}><Link href="/login">Back to sign in</Link></p></AuthFrame>; }
